// <auto-generated />
using System;
using CampusShare.Web.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusShare.Web.Migrations
{
    [DbContext(typeof(CampusShareDBContext))]
    [Migration("20251105224036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusShare.Web.Models.Articulo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoArticulo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("CampusShare.Web.Models.Prestamo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlumnoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticuloId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EstadoPrestamo")
                        .HasColumnType("int");

                    b.Property<string>("FecFin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FecInicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("ArticuloId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("CampusShare.Web.Models.Reserva", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlumnoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlumnoId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticuloId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EstadoReserva")
                        .HasColumnType("int");

                    b.Property<string>("FecFin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FecInicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AlumnoId1");

                    b.HasIndex("ArticuloId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("CampusShare.Web.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CampusShare.Web.Models.Admin", b =>
                {
                    b.HasBaseType("CampusShare.Web.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("CampusShare.Web.Models.Alumno", b =>
                {
                    b.HasBaseType("CampusShare.Web.Models.User");

                    b.HasDiscriminator().HasValue("Alumno");
                });

            modelBuilder.Entity("CampusShare.Web.Models.Prestamo", b =>
                {
                    b.HasOne("CampusShare.Web.Models.Alumno", null)
                        .WithMany("PrestamosHistorial")
                        .HasForeignKey("AlumnoId");

                    b.HasOne("CampusShare.Web.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("CampusShare.Web.Models.Reserva", b =>
                {
                    b.HasOne("CampusShare.Web.Models.Alumno", "Alumno")
                        .WithMany("Reservas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CampusShare.Web.Models.Alumno", null)
                        .WithMany("ReservasHistorial")
                        .HasForeignKey("AlumnoId1");

                    b.HasOne("CampusShare.Web.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId");

                    b.Navigation("Alumno");

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("CampusShare.Web.Models.Alumno", b =>
                {
                    b.Navigation("PrestamosHistorial");

                    b.Navigation("Reservas");

                    b.Navigation("ReservasHistorial");
                });
#pragma warning restore 612, 618
        }
    }
}
